# zshrc is also sourced when the shell is started programatically

# add .config/bin to path and then export to sub-processes can use it
export PATH="$HOME/.config/bin/:$PATH"

# make homebrew and its libraries available
eval "$(/opt/homebrew/bin/brew shellenv)"

# don't set ZDOTDIR to this directory, to not save cache files/history here
export ZSHCONFIG="$HOME/.config/zsh"

# set default editor
export EDITOR=nvim
export VISUAL=nvim

# should not be necessary if the program is in the path? but check if maybe node doesn't add it?
# export LAUNCH_EDITOR=launch_nvim
