# zshrc is only sourced for interactive shells
#
# initialize pretty prompt with starship
eval "$(starship init zsh)"
# initialize direnv
eval "$(direnv hook zsh)"
# initialize fnm (fast node manager)
eval "$(fnm env --use-on-cd --shell zsh)"
# initialize zim (package manager for zsh)
source ${ZSHCONFIG}/zim/init.zsh

alias vi=nvim_auto_restart

function vic {
  cd ~/.config && vi
}

export FZF_ALT_C_COMMAND='fd --type d . $HOME'
bindkey '\ex' fzf-cd-widget

bindkey -s '^g' '^ugit_checkout_fzf^M'
